- name: "5.1 Ensure Options for the OS Root Directory Are Restricted (Scored)"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '<Directory />'
    regexp: '^Options None'
    line: '     Options None'
  notify:
    - restart httpd
  tags:
    - cis-5.1
    - cis-5.2
    - cis-5.3
    - section-5
- name: "5.4 Ensure Default HTML Content Is Removed (Scored)"
  copy:
    src: welcome.conf.j2
    dest: /etc/httpd/conf.d/welcome.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
  tags:
    - cis-5.4
    - section-5

- name: "5.5 Ensure the Default CGI Content printenv Script Is Removed (Scored)"
  debug:
    msg: "Removed By default"
  tags:
    - cis-5.5
    - section-4
- name: "5.6 Ensure the Default CGI Content test-cgi Script Is Removed (Scored)"
  debug:
    msg: "Removed By default"
  tags:
    - cis-5.6
    - section-5
- name: "5.7 Ensure HTTP Request Methods Are Restricted (Scored)"
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: '<Directory "/var/www/html">'
    block: |
      <LimitExcept GET POST OPTIONS>
          Require all denied
      </LimitExcept>
  notify:
    - restart httpd
  tags:
    - cis-5.7
    - section-5
- name: "5.8 Ensure the HTTP TRACE Method Is Disabled (Scored)"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: 'TraceEnable off'
    state: present
    insertafter: 'EnableSendfile on'
  notify:
    - restart httpd
  tags:
    - cis-5.8
    - section-5
- name: "5.9 Ensure Old HTTP Protocol Versions Are Disallowed (Scored)"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: 'TraceEnable off'
    line: '{{ item }}'
  with_items:
    - RewriteEngine On
    - RewriteCond %{THE_REQUEST} !HTTP/1\.1$
    - RewriteRule .* - [F]
  notify:
    - restart httpd
  tags:
    - cis-5.9
    - section-5
- name: "5.10 Ensure Access to .ht* Files Is Restricted (Scored)"
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^<Files\s\".ht\*\">'
    replace: '<FilesMatch "^\.ht">'
  notify:
    - restart httpd
  tags:
    - cis-5.10
    - section-5
- name: "5.10 Ensure Access to .ht* Files Is Restricted (Scored)"
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^(</Files>)$'
    replace: '</FilesMatch>'
  notify:
    - restart httpd
  tags:
    - cis-5.10
    - section-5

- name: "5.11 Ensure Access to Inappropriate File Extensions Is Restricted (Scored)"
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: EOF
    state : present
    create: yes
    block: |
        <FilesMatch "^.*\.(css|html?|js|pdf|txt|xml|xsl|gif|ico|jpe?g|png)$">
                 Require all granted
        </FilesMatch>
  notify:
    - restart httpd
  tags:
    - cis-5.11
    - section-5
- name: "5.14 Ensure Browser Framing Is Restricted (Scored)"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertafter: 'TraceEnable off'
    line: 'Header always append X-Frame-Options SAMEORIGIN' 
    state: present
  notify:
    - restart httpd
  tags:
    - cis-5.14
    - section-5
