- name: "Install Epel-release"
  yum:
    name: epel-release
    state: latest
  tags:
    - cis-1.1
    - section-1
- name: "1.3 Ensure Apache Is Installed From the Appropriate Binaries (NotScored)"
  yum:
    name: httpd
    state: latest
  notify:
    - start httpd
    - restart httpd
  tags:
    - cis-1.3
    - section-1
